### ISSUE TITLE
Use jars provided by genie

### ISSUE THREAD

**Issue by MSeal** [mpacer/almond#4]

**Comment by mpacer** [comment]
I changed the title of this to reflect what I think it originally meant which was to use the jars that genie provides via a download. 

This works by using the `interp.load.cp` with the appropriate values. 

Right now what works is getting everything inside the `sys.env("SPARK_HOME") + "/jars/"` and the hadoop directories defined by `s"""${sys.env("HADOOP_HOME")}/bin/hadoop classpath""".!!` (where `!!` is scala's way of running a subprocess from a string). 

Then we need to treat the response from hadoop differently… with entries that end with `/` to be added to the classpath directly (`interp.load.cp("dirName/")`) and grabbing the jars from within entries ending with a `*` (`for(fileName <- filesInDir("jarDirName/*")){interp.load.cp(filename)}`). 

This doesn't actually connect to yarn though… for that we also need to access the spark properties. But that's a different issue.
